

###
get http://localhost:3000/users

###
get http://localhost:3000/users/2

###

 delete http://localhost:3000/users/5 HTTP/1.1

###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "email":"hamza.braimi33@gmail.com",
    "nom": "HAMZA",
    "password": "12345678"
}

###

POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json
Authorization: Bearer

{
    
    "email":"hamza.braimi33@gmail.com",
    "password":"12345678"
}
###
PATCH http://localhost:3000/users HTTP/1.1
content-type: application/json
Authorization: Bearer

{
    "id":1,
    "nom":"nfnffnfnfn",
    "password":"nfnf",
    "description":"j'aime bien de naviguer"
}

###




